Author: Ishika Wikramanayake

Start_Date: 26-Aug-2019

End_Date: 30-Aug-2019

### Import libraries

In [1]:
import pandas as pd
import folium

In [2]:


# ACT


Bats = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Bats.csv")

Mammals_1988 = Bats


Herbivorous_Marsupials = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])
Carnivorous_Marsupials = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])

Monotremes = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])


Rodents = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])

Hares__Pikas__Rabbits = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Hares__Pikas__Rabbits.csv")
Mammals_1988 = pd.concat([Mammals_1988, Hares__Pikas__Rabbits])

Carnivores = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Carnivores.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivores])



# NSW

Bandicoots__Bilbies = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Bandicoots__Bilbies.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bandicoots__Bilbies])

Bats = pd.read_csv("./Datasets/AUSTRALIAN CAPITAL TERRITORY/1988/Mammals/Bats.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bats])

Carnivores = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Carnivores.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivores])

Carnivorous_Marsupials = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])

Even_toed_hoofed = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Even-toed_hoofed.csv")
Mammals_1988 = pd.concat([Mammals_1988, Even_toed_hoofed])

Hares__Pikas__Rabbits = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Hares__Pikas__Rabbits.csv")
Mammals_1988 = pd.concat([Mammals_1988, Hares__Pikas__Rabbits])

Herbivorous_Marsupials = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])

Monotremes = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])

Rodents = pd.read_csv("./Datasets/NEW SOUTH WALES/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])


# NT
Bandicoots__Bilbies = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Bandicoots__Bilbies.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bandicoots__Bilbies])

Bats = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Bats.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bats])

Carnivores = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Carnivores.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivores])

Carnivorous_Marsupials = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])

Even_toed_hoofed = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Even-toed_hoofed.csv")
Mammals_1988 = pd.concat([Mammals_1988, Even_toed_hoofed])


Herbivorous_Marsupials = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])

Marsupial_Moles = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Marsupial_Moles.csv")
Mammals_1988 = pd.concat([Mammals_1988, Marsupial_Moles])

Rodents = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])

Monotremes = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])

Monotremes = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])

Hares__Pikas__Rabbits = pd.read_csv("./Datasets/NORTHERN TERRITORY/1988/Mammals/Hares__Pikas__Rabbits.csv")
Mammals_1988 = pd.concat([Mammals_1988, Hares__Pikas__Rabbits])


# QLD
Bandicoots__Bilbies = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Bandicoots__Bilbies.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bandicoots__Bilbies])

Bats = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Bats.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bats])

Carnivores = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Carnivores.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivores])

Carnivorous_Marsupials = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])

Even_toed_hoofed = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Even-toed_hoofed.csv")
Mammals_1988 = pd.concat([Mammals_1988, Even_toed_hoofed])

Hares__Pikas__Rabbits = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Hares__Pikas__Rabbits.csv")
Mammals_1988 = pd.concat([Mammals_1988, Hares__Pikas__Rabbits])

Herbivorous_Marsupials = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])

Monotremes = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])

Rodents = pd.read_csv("./Datasets/QUEENSLAND/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])



# SA

Bandicoots__Bilbies = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Bandicoots__Bilbies.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bandicoots__Bilbies])

Bats = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Bats.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bats])

Carnivores = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Carnivores.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivores])

Carnivorous_Marsupials = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])

Even_toed_hoofed = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Even-toed_hoofed.csv")
Mammals_1988 = pd.concat([Mammals_1988, Even_toed_hoofed])

Hares__Pikas__Rabbits = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Hares__Pikas__Rabbits.csv")
Mammals_1988 = pd.concat([Mammals_1988, Hares__Pikas__Rabbits])

Herbivorous_Marsupials = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])

Monotremes = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])

Rodents = pd.read_csv("./Datasets/SOUTH AUSTRALIA/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])


# TAS
Bandicoots__Bilbies = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Bandicoots__Bilbies.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bandicoots__Bilbies])

Bats = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Bats.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bats])

Carnivores = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Carnivores.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivores])

Carnivorous_Marsupials = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])

Hares__Pikas__Rabbits = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Hares__Pikas__Rabbits.csv")
Mammals_1988 = pd.concat([Mammals_1988, Hares__Pikas__Rabbits])

Herbivorous_Marsupials = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])

Rodents = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])

Monotremes = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])

Even_toed_hoofed = pd.read_csv("./Datasets/TASMANIA/1988/Mammals/Even-toed_hoofed.csv")
Mammals_1988 = pd.concat([Mammals_1988, Even_toed_hoofed])



# VIC
Bandicoots__Bilbies = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Bandicoots__Bilbies.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bandicoots__Bilbies])

Bats = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Bats.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bats])

Carnivores = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Carnivores.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivores])

Carnivorous_Marsupials = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])


Even_toed_hoofed = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Even-toed_hoofed.csv")
Mammals_1988 = pd.concat([Mammals_1988, Even_toed_hoofed])

Hares__Pikas__Rabbits = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Hares__Pikas__Rabbits.csv")
Mammals_1988 = pd.concat([Mammals_1988, Hares__Pikas__Rabbits])

Herbivorous_Marsupials = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])

Monotremes = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Monotremes.csv")
Mammals_1988 = pd.concat([Mammals_1988, Monotremes])

Rodents = pd.read_csv("./Datasets/VICTORIA/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])


# WA
Bandicoots__Bilbies = pd.read_csv("./Datasets/WESTERN AUSTRALIA/1988/Mammals/Bandicoots__Bilbies.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bandicoots__Bilbies])

Bats = pd.read_csv("./Datasets/WESTERN AUSTRALIA/1988/Mammals/Bats.csv")
Mammals_1988 = pd.concat([Mammals_1988, Bats])

Carnivorous_Marsupials = pd.read_csv("./Datasets/WESTERN AUSTRALIA/1988/Mammals/Carnivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Carnivorous_Marsupials])

Herbivorous_Marsupials = pd.read_csv("./Datasets/WESTERN AUSTRALIA/1988/Mammals/Herbivorous_Marsupials.csv")
Mammals_1988 = pd.concat([Mammals_1988, Herbivorous_Marsupials])

Rodents = pd.read_csv("./Datasets/WESTERN AUSTRALIA/1988/Mammals/Rodents.csv")
Mammals_1988 = pd.concat([Mammals_1988, Rodents])

### 1988

In [3]:
# Drop unnecessary columns in 1988

Mammals_1988 = Mammals_1988.drop(columns=['Record ID', 'Catalogue Number', 'Taxon Concept GUID', 'Scientific Name - original', 'Species', 'Subspecies', 'Institution ID', 'Institution', 'Collection ID', 'Collection', 'Locality', 'Coordinate Precision', 'IMCRA 4 Regions', 'Minimum elevation in meters', 'Local Government Areas 2011', 'Maximum elevation in meters', 'Minimum depth in meters', 'Maximum depth in meters', 'Sex', 'Preparations', 'Outlier for layer', 'Data Resource ID', 'Data Resource Name', 'Licence', 'Institution Code', 'Collection Code', 'Geodetic datum - original', 'Coordinate Uncertainty in Metres', 'Individual count', 'Collector', 'Month', 'Day', 'Event Date - parsed', 'Verbatim event date', 'Basis Of Record - original', 'Basis Of Record', 'Occurrence status', 'Taxonomic Quality', 'Order', 'IBRA 7 Regions', 'Location Quality', 'Latitude - original', 'Longitude - original', 'Vernacular name'])

In [4]:
# Check how many null values are in their in all the columns for 1988

Mammals_1988.isnull().sum()

Vernacular name - original    795
Scientific Name                 0
Taxon Rank                      0
Kingdom                         0
Phylum                          0
Class                           0
Family                          0
Genus                           0
Latitude                        0
Longitude                       0
Country - parsed                0
State - parsed                  0
Year                            0
dtype: int64

In [5]:
# Manually add the English names to the rows with null values for 1988

Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Phascolarctos cinereus', 'Vernacular name - original'] = 'Koala'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Macropus giganteus', 'Vernacular name - original'] = 'Eastern grey kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Trichosurus vulpecula', 'Vernacular name - original'] = 'Brushtail possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Tachyglossus aculeatus', 'Vernacular name - original'] = 'Short-beaked echidna'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Wallabia bicolor', 'Vernacular name - original'] = 'Swamp wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pseudocheirus peregrinus', 'Vernacular name - original'] = 'Ringtail possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Macropus fuliginosus', 'Vernacular name - original'] = 'Western grey kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Vulpes vulpes', 'Vernacular name - original'] = 'Red fox'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Oryctolagus cuniculus', 'Vernacular name - original'] = 'European rabbit'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Chenonetta jubata', 'Vernacular name - original'] = 'Australian wood duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pteropus poliocephalus', 'Vernacular name - original'] = 'Grey-headed flying fox'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas superciliosa Gmelin', 'Vernacular name - original'] = 'Pacific black duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'superciliosa', 'Vernacular name - original'] = 'Pacific black duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Macropus rufogriseus', 'Vernacular name - original'] = 'Red-necked wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Cygnus (Chenopis) atratus', 'Vernacular name - original'] = 'Black swan'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Thylogale stigmatica', 'Vernacular name - original'] = 'Red-legged pademelon'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notamacropus agilis', 'Vernacular name - original'] = 'Agile wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Ornithorhynchus anatinus', 'Vernacular name - original'] = 'Platypus'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dama dama', 'Vernacular name - original'] = 'Fallow deer'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Vombatus ursinus', 'Vernacular name - original'] = 'Common wombat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notamacropus rufogriseus', 'Vernacular name - original'] = 'Red-necked wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas (Nettion) castanea', 'Vernacular name - original'] = 'Chestnut teal'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pteropus conspicillatus conspicillatus', 'Vernacular name - original'] = 'Spectacled flying fox'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Aythya (Nyroca) australis', 'Vernacular name - original'] = 'Hardhead duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas (Anas) superciliosa', 'Vernacular name - original'] = 'Pacific black duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petaurus breviceps breviceps', 'Vernacular name - original'] = 'Sugar glider'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pteropus alecto', 'Vernacular name - original'] = 'Black flying fox'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Black flying fox', 'Vernacular name - original'] = 'name'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Canis familiaris', 'Vernacular name - original'] = 'Domestic Dog'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Isoodon obesulus', 'Vernacular name - original'] = 'Southern brown bandicoot'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petauroides volans', 'Vernacular name - original'] = 'Greater glider'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Osphranter robustus robustus', 'Vernacular name - original'] = 'Wallaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Vulpes vulpes vulpes', 'Vernacular name - original'] = 'Red fox'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Antechinus swainsonii', 'Vernacular name - original'] = 'Dusky antechinus'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dasyurus maculatus maculatus', 'Vernacular name - original'] = 'Tiger quoll'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Falsistrellus tasmaniensis', 'Vernacular name - original'] = 'Eastern false pipistrelle'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notomys mitchellii', 'Vernacular name - original'] = 'Spinifex hopping mouse'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Falsistrellus tasmaniensis', 'Vernacular name - original'] = 'Eastern false pipistrelle'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Canis lupus', 'Vernacular name - original'] = 'Wolf'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Macrotis lagotis', 'Vernacular name - original'] = 'Greater bilby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notomys alexis alexis', 'Vernacular name - original'] = 'Spinifex hopping mouse'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Conilurus penicillatus', 'Vernacular name - original'] = 'Brush-tailed rabbit rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Isoodon fusciventer', 'Vernacular name - original'] = 'Southern brown bandicoot'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pseudomys australis', 'Vernacular name - original'] = 'Plains rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Melomys cervinipes', 'Vernacular name - original'] = 'Fawn-footed mosaic-tailed rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Xeromys myoides', 'Vernacular name - original'] = 'False water rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Osphranter antilopinus', 'Vernacular name - original'] = 'Antilopine kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Xeromys myoides', 'Vernacular name - original'] = 'False water rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Osphranter antilopinus', 'Vernacular name - original'] = 'Antilopine kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Phascogale tapoatafa wambenger', 'Vernacular name - original'] = 'Brush-tailed phascogale'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Biziura lobata', 'Vernacular name - original'] = 'Musk duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Mormopterus (Ozimops) kitcheneri', 'Vernacular name - original'] = 'south-western free-tailed bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Sminthopsis murina', 'Vernacular name - original'] = 'Slender-tailed dunnart'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Vombatus ursinus tasmaniensis', 'Vernacular name - original'] = 'Wombat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale lateralis', 'Vernacular name - original'] = 'Black-flanked rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Osphranter bernardus', 'Vernacular name - original'] = 'Wallaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Antechinus stuartii', 'Vernacular name - original'] = 'Brown antechinus'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Delphinus delphis delphis', 'Vernacular name - original'] = 'Short-beaked common dolphin'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas acuta', 'Vernacular name - original'] = 'Northern pintail'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Antechinus flavipes leucogaster', 'Vernacular name - original'] = 'Yellow-footed antechinus'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale xanthopus', 'Vernacular name - original'] = 'Yellow-footed rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Zyzomys argurus', 'Vernacular name - original'] = 'Rock rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anser anser', 'Vernacular name - original'] = 'Greylag goose'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Austronomus australis', 'Vernacular name - original'] = 'White-striped free-tailed bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Phascogale calura', 'Vernacular name - original'] = 'Red-tailed phascogale'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Thylogale thetis', 'Vernacular name - original'] = 'Red-necked pademelon'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Hemibelideus lemuroides', 'Vernacular name - original'] = 'Lemur-like ringtail possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Phascolarctos cinereus adustus', 'Vernacular name - original'] = 'Koala'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Hypsiprymnodon moschatus', 'Vernacular name - original'] = 'Musky rat-kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dendrolagus lumholtzi', 'Vernacular name - original'] = 'Lumholtz\'s tree-kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dactylopsila trivirgata', 'Vernacular name - original'] = 'Striped possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petaurus australis', 'Vernacular name - original'] = 'Yellow-bellied glider'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale purpureicollis', 'Vernacular name - original'] = 'Purple-necked rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pseudochirops archeri', 'Vernacular name - original'] = 'Pseudochirops archeri'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Trichosurus cunninghami', 'Vernacular name - original'] = 'Mountain brushtail possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Wyulda squamicaudata', 'Vernacular name - original'] = 'Scaly-tailed possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notamacropus dorsalis', 'Vernacular name - original'] = 'Black-striped Wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dactylopsila trivirgata picata', 'Vernacular name - original'] = 'Striped possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale herberti', 'Vernacular name - original'] = 'Herbert\'s rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Macroderma gigas', 'Vernacular name - original'] = 'Ghost bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Chaerephon jobensis', 'Vernacular name - original'] = 'Northern freetail bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Hipposideros ater', 'Vernacular name - original'] = 'Dusky leaf-nosed bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Miniopterus australis', 'Vernacular name - original'] = 'Little bent-wing bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Miniopterus schreibersii', 'Vernacular name - original'] = 'Common bent-wing bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Saccolaimus saccolaimus nudicluniatus', 'Vernacular name - original'] = 'Bare-rumped sheathtail bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Rhinolophus megaphyllus megaphyllus', 'Vernacular name - original'] = 'Smaller horseshoe bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Scoteanax rueppellii', 'Vernacular name - original'] = 'Rüppell\'s broad-nosed bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Nyctimene robinsoni', 'Vernacular name - original'] = 'Eastern tube-nosed bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Canis lupus familiaris', 'Vernacular name - original'] = 'Dog'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Lepus capensis', 'Vernacular name - original'] = 'Cape hare'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dasyurus hallucatus', 'Vernacular name - original'] = 'Northern quoll'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Cervus elaphus', 'Vernacular name - original'] = 'Red deer'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Cervus timorensis', 'Vernacular name - original'] = 'Javan rusa'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Phascogale tapoatafa tapoatafa', 'Vernacular name - original'] = 'Brush-tailed phascogale'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Cervus nippon', 'Vernacular name - original'] = 'Sika deer'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Phascogale tapoatafa', 'Vernacular name - original'] = 'Brush-tailed phascogale'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dama dama dama', 'Vernacular name - original'] = 'Persian fallow deer'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Capra hircus', 'Vernacular name - original'] = 'Feral goat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Rattus fuscipes', 'Vernacular name - original'] = 'Bush rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Axis axis', 'Vernacular name - original'] = 'Chital'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Isoodon obesulus obesulus', 'Vernacular name - original'] = 'Southern brown bandicoot'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Chalinolobus gouldii', 'Vernacular name - original'] = 'Gould\'s wattled bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Phascolarctos cinereus victor', 'Vernacular name - original'] = 'Koala'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale xanthopus xanthopus', 'Vernacular name - original'] = 'Yellow-footed rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Lasiorhinus latifrons', 'Vernacular name - original'] = 'Southern hairy-nosed wombat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Cercartetus concinnus', 'Vernacular name - original'] = 'Western pygmy possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notamacropus eugenii', 'Vernacular name - original'] = 'Tammar wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Rattus lutreolus', 'Vernacular name - original'] = 'Australian swamp rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Perameles gunnii', 'Vernacular name - original'] = 'Eastern barred bandicoot'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Vespadelus regulus', 'Vernacular name - original'] = 'Southern forest bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Sarcophilus harrisii', 'Vernacular name - original'] = 'Tasmanian devil'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Thylogale billardierii', 'Vernacular name - original'] = 'Tasmanian pademelon'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Macropus rufogriseus rufogriseus', 'Vernacular name - original'] = 'Red-necked wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Bettongia gaimardi', 'Vernacular name - original'] = 'Eastern bettong'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Vespadelus darlingtoni', 'Vernacular name - original'] = 'Large forest bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Chalinolobus morio', 'Vernacular name - original'] = 'Chocolate wattled bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dasyurus geoffroii geoffroii', 'Vernacular name - original'] = 'Western quoll'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Myrmecobius fasciatus fasciatus', 'Vernacular name - original'] = 'Numbat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pseudocheirus occidentalis', 'Vernacular name - original'] = 'Western ringtail possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Tarsipes rostratus', 'Vernacular name - original'] = 'Honey possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Setonix brachyurus', 'Vernacular name - original'] = 'Quokka'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notamacropus irma', 'Vernacular name - original'] = 'Western brush wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Bettongia penicillata penicillata', 'Vernacular name - original'] = 'Woylie'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Felis catus', 'Vernacular name - original'] = 'Cat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Antechinus agilis', 'Vernacular name - original'] = 'Agile antechinus'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Lepus europaeus', 'Vernacular name - original'] = 'European hare'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Potorous tridactylus', 'Vernacular name - original'] = 'Long-nosed potoroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Hydromys chrysogaster', 'Vernacular name - original'] = 'Rakali'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Perameles nasuta', 'Vernacular name - original'] = 'Long-nosed bandicoot'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Isoodon macrourus', 'Vernacular name - original'] = 'Northern brown bandicoot'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Nyctophilus geoffroyi geoffroyi', 'Vernacular name - original'] = 'Lesser long-eared bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Pteropus scapulatus', 'Vernacular name - original'] = 'Little red flying fox'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Vespadelus vulturnus', 'Vernacular name - original'] = 'Little forest bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Myotis macropus', 'Vernacular name - original'] = 'Myotis macropus'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Nyctophilus bifax', 'Vernacular name - original'] = 'Eastern long-eared bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Neophoca cinerea', 'Vernacular name - original'] = 'Australian sea lion'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Arctocephalus pusillus doriferus', 'Vernacular name - original'] = 'Australian fur seals'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petaurus norfolcensis', 'Vernacular name - original'] = 'Squirrel glider'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Rattus rattus', 'Vernacular name - original'] = 'Black rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Bos (Bos) taurus', 'Vernacular name - original'] = 'European cattle'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Antechinus flavipes', 'Vernacular name - original'] = 'Yellow-footed antechinus'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Camelus dromedarius', 'Vernacular name - original'] = 'Dromedary'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Acrobates pygmaeus', 'Vernacular name - original'] = 'Feathertail glider'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Sminthopsis crassicaudata', 'Vernacular name - original'] = 'Fat-tailed dunnart'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dasyurus viverrinus', 'Vernacular name - original'] = 'Eastern quoll'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Tursiops aduncus', 'Vernacular name - original'] = 'Indo-Pacific bottlenose dolphin'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dasyurus maculatus', 'Vernacular name - original'] = 'Tiger quoll'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Lagorchestes hirsutus', 'Vernacular name - original'] = 'Rufous hare-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Mus musculus', 'Vernacular name - original'] = 'House mouse'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Onychogalea fraenata', 'Vernacular name - original'] = 'Bridled nail-tail wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Trichosurus caninus', 'Vernacular name - original'] = 'Short-eared possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Rattus norvegicus', 'Vernacular name - original'] = 'Brown rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Sus scrofa', 'Vernacular name - original'] = 'Wild boar'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Osphranter robustus', 'Vernacular name - original'] = 'Common wallaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Osphranter rufus', 'Vernacular name - original'] = 'Red kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale penicillata', 'Vernacular name - original'] = 'Brush-tailed rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Aepyprymnus rufescens', 'Vernacular name - original'] = 'Rufous rat-kangaroo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Notamacropus parryi', 'Vernacular name - original'] = 'Whiptail wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas (Nettion) gracilis', 'Vernacular name - original'] = 'Grey teal'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas superciliosa Gmelin, 1789 superciliosa', 'Vernacular name - original'] = 'Pacific black duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dendrocygna (Dendrocygna) arcuata', 'Vernacular name - original'] = 'Wandering whistling duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Malacorhynchus membranaceus', 'Vernacular name - original'] = 'Pink-eared duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas (Anas) platyrhynchos', 'Vernacular name - original'] = 'Mallard'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dendrocygna (Leptotarsis) eytoni', 'Vernacular name - original'] = 'Plumed whistling duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas platyrhynchos domesticus', 'Vernacular name - original'] = 'Domestic duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anas platyrhynchos Linnaeus, 1758 platyrhynchos', 'Vernacular name - original'] = 'Mallard'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anser anser domesticus', 'Vernacular name - original'] = 'Domestic goose'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Anseranas semipalmata', 'Vernacular name - original'] = 'Magpie goose'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Stictonetta naevosa', 'Vernacular name - original'] = 'Freckled duck'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Rhinonicteris aurantia', 'Vernacular name - original'] = 'Orange leaf-nosed bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Macroglossus minimus', 'Vernacular name - original'] = 'Long-tongued nectar bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Nyctophilus arnhemensis', 'Vernacular name - original'] = 'Arnhem long-eared bat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Dugong dugon', 'Vernacular name - original'] = 'Dugong'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Bubalus bubalis', 'Vernacular name - original'] = 'Water buffalo'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale lateralis lateralis', 'Vernacular name - original'] = 'Black-flanked rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petropseudes dahli', 'Vernacular name - original'] = 'Rock-haunting ringtail possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Onychogalea unguifera', 'Vernacular name - original'] = 'Northern nail-tail wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Petrogale brachyotis brachyotis', 'Vernacular name - original'] = 'Short-eared rock-wallaby'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Trichosurus vulpecula vulpecula', 'Vernacular name - original'] = 'Common brushtail possum'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Mesembriomys gouldii', 'Vernacular name - original'] = 'Black-footed tree-rat'
Mammals_1988.loc[Mammals_1988['Scientific Name'] == 'Melomys burtoni', 'Vernacular name - original'] = 'Grassland mosaic-tailed rat'

In [6]:
# Take the rows where the English name is not null in 1988

Mammals_1988 = Mammals_1988[Mammals_1988['Vernacular name - original'].notnull()]

In [7]:
# Read 2019 data for amphibians, mammals and reptiles

Amphibians_2019 = pd.read_csv("ANIMALS.csv")

In [8]:
# Calculate the frequency of the English names for 1988
 
Mammals_1988['freq'] = Mammals_1988.groupby('Vernacular name - original')['Vernacular name - original'].transform('count')

# Drop rows with English name duplicates in 1988

Mammals_1988.drop_duplicates(subset ="Vernacular name - original", keep = "first", inplace = True)

In [9]:
# Check the first 5 rows in 1988

Mammals_1988.head()

,Vernacular name - original,Scientific Name,Taxon Rank,Kingdom,Phylum,Class,Family,Genus,Latitude,Longitude,Country - parsed,State - parsed,Year,freq
0,Common bent-wing bat,Miniopterus schreibersii,species,Animalia,Chordata,Mammalia,Miniopteridae,Miniopterus,-35.2333,149.0417,Australia,Australian Capital Territory,1988,554
1,Gould's wattled bat,Chalinolobus gouldii,species,Animalia,Chordata,Mammalia,Vespertilionidae,Chalinolobus,-35.1667,149.0667,Australia,Australian Capital Territory,1988,437
2,Lesser long-eared bat,Nyctophilus geoffroyi geoffroyi,subspecies,Animalia,Chordata,Mammalia,Vespertilionidae,Nyctophilus,-35.4260,149.0780,Australia,Australian Capital Territory,1988,470
0,Feathertail glider,Acrobates pygmaeus,species,Animalia,Chordata,Mammalia,Acrobatidae,Acrobates,-35.6040,148.8210,Australia,Australian Capital Territory,1988,34
1,Common wombat,Vombatus ursinus,species,Animalia,Chordata,Mammalia,Vombatidae,Vombatus,-35.3410,149.2290,Australia,Australian Capital Territory,1988,257

In [10]:
# Add the frequency in 1988 to 2019

for index, row in Amphibians_2019.iterrows():
    species = row['Vernacular name - original']
    if any(Mammals_1988['Vernacular name - original'] == species):
        Amphibians_2019.at[index,'1988'] = Mammals_1988.loc[Mammals_1988['Vernacular name - original'] == species, 'freq'].iloc[0]

In [11]:
# Check the first 5 rows in 2019

Amphibians_2019.head()

,Vernacular name - original,Scientific Name,Taxon Rank,Kingdom,Phylum,Class,Family,Genus,Latitude,Longitude,...,Year,freq,Count_1968,Rate_1968,No,1978,1988,1998,2008,2018
0,Slender-tailed dunnart,Sminthopsis murina,species,Animalia,Chordata,Mammalia,Dasyuridae,Sminthopsis,-29.539333,153.090917,...,2019,3,2109,-99.857752,1,18.0,36.0,NaN,NaN,NaN
1,Slender-tailed dunnart,Sminthopsis murina,species,Animalia,Chordata,Mammalia,Dasyuridae,Sminthopsis,-32.380600,151.013600,...,2019,3,2109,-99.857752,1,18.0,36.0,NaN,NaN,NaN
2,Slender-tailed dunnart,Sminthopsis murina,species,Animalia,Chordata,Mammalia,Dasyuridae,Sminthopsis,-34.500000,150.400000,...,2019,3,2109,-99.857752,1,18.0,36.0,NaN,NaN,NaN
3,Common Planigale,Planigale maculata,species,Animalia,Chordata,Mammalia,Dasyuridae,Planigale,-29.633753,153.216922,...,2019,1,283,-99.646643,2,12.0,25.0,NaN,NaN,NaN
4,Gehyra variegata,Gehyra variegata,species,Animalia,Chordata,Reptilia,Gekkonidae,Gehyra,-31.960032,116.032948,...,2019,1,185,-99.459459,3,NaN,NaN,NaN,NaN,NaN

In [12]:
# Update the 2019 file

Amphibians_2019.to_csv('ANIMALS.csv', sep=',', encoding='utf-8', index = False)